name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Clone JADX
        uses: actions/checkout@v4
        with:
          repository: skylot/jadx
          path: jadx

      - name: Build JADX
        run: cd ./jadx && ./gradlew copyArtifacts

      - name: Move JADX JAR
        run: mv ./jadx/build/jadx/lib/jadx-dev-all.jar ./jadx.jar

      - name: Build plugin JAR
        run: ./gradlew shadowJar

      - name: Test plugin
        run: ./gradlew test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jadx-type-diagram-plugin
          path: ./build/libs/*.jar


